spring.application.name=quickseat
spring.profiles.default=dev

server.servlet.context-path=/api/v1

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.booking.hold-duration-minutes=${SEAT_HOLD_DURATION_MINUTES:5}
app.booking.hold-cleanup-interval-ms=${SEAT_HOLD_CLEANUP_INTERVAL_MS:60000}
